apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: exam
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # "postgres" encodé en base64
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # "password" encodé en base64
  POSTGRES_DB: RXR1ZGlhbnRz  # "Etudiants" encodé en base64
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: exam
spec:
  serviceName: "postgres-service"
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: abdelkrims/postgres:latest
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"  
            cpu: "250m"      
          limits:
            memory: "512Mi"  
            cpu: "500m"      
        livenessProbe:
          httpGet:
            path: /health
            port: 5432
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 5432
          initialDelaySeconds: 5
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /health
            port: 5432
          initialDelaySeconds: 15
          periodSeconds: 20
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: exam
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
