apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: multi-app-pdb
  namespace: exam
spec:
  minAvailable: 1
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - frontend
      - backend
      - postgres
