apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: exam-resources-access
  namespace: exam
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: exam-resources-access-binding
  namespace: exam
subjects:
- kind: User
  name: "Abdelkrim"  
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: exam-resources-access
  apiGroup: rbac.authorization.k8s.io
